[2022-10-17 10:38:27,525] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.is_api_available backfill__2022-01-11T00:00:00+00:00 [queued]>
[2022-10-17 10:38:27,554] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.is_api_available backfill__2022-01-11T00:00:00+00:00 [queued]>
[2022-10-17 10:38:27,563] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:38:27,564] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-17 10:38:27,564] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:38:27,588] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-01-11 00:00:00+00:00
[2022-10-17 10:38:27,596] {standard_task_runner.py:52} INFO - Started process 4308 to run task
[2022-10-17 10:38:27,634] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'is_api_available', 'backfill__2022-01-11T00:00:00+00:00', '--job-id', '126', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpaf5rnjj9', '--error-file', '/tmp/tmpdpcyhesx']
[2022-10-17 10:38:27,644] {standard_task_runner.py:80} INFO - Job 126: Subtask is_api_available
[2022-10-17 10:38:27,975] {task_command.py:369} INFO - Running <TaskInstance: my_first_dag.is_api_available backfill__2022-01-11T00:00:00+00:00 [running]> on host 48b5b9061ccc
[2022-10-17 10:38:28,544] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-01-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=backfill__2022-01-11T00:00:00+00:00
[2022-10-17 10:38:28,547] {http.py:97} INFO - Poking: users/
[2022-10-17 10:38:28,590] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-10-17 10:38:28,624] {http.py:129} INFO - Sending 'GET' to url:  https://random-data-api.com/api/v2/users/
[2022-10-17 10:38:29,706] {base.py:301} INFO - Success criteria met. Exiting.
[2022-10-17 10:38:29,749] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=is_api_available, execution_date=20220111T000000, start_date=20221017T103827, end_date=20221017T103829
[2022-10-17 10:38:29,930] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-17 10:38:30,045] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
