[2022-10-17 10:38:28,653] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.is_api_available backfill__2022-01-02T00:00:00+00:00 [queued]>
[2022-10-17 10:38:28,689] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.is_api_available backfill__2022-01-02T00:00:00+00:00 [queued]>
[2022-10-17 10:38:28,690] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:38:28,690] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-17 10:38:28,691] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:38:28,748] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-01-02 00:00:00+00:00
[2022-10-17 10:38:28,767] {standard_task_runner.py:52} INFO - Started process 4317 to run task
[2022-10-17 10:38:28,790] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'is_api_available', 'backfill__2022-01-02T00:00:00+00:00', '--job-id', '134', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmprvd8ils7', '--error-file', '/tmp/tmp2yoyvtgs']
[2022-10-17 10:38:28,794] {standard_task_runner.py:80} INFO - Job 134: Subtask is_api_available
[2022-10-17 10:38:28,950] {task_command.py:369} INFO - Running <TaskInstance: my_first_dag.is_api_available backfill__2022-01-02T00:00:00+00:00 [running]> on host 48b5b9061ccc
[2022-10-17 10:38:29,158] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-01-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=backfill__2022-01-02T00:00:00+00:00
[2022-10-17 10:38:29,165] {http.py:97} INFO - Poking: users/
[2022-10-17 10:38:29,187] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-10-17 10:38:29,195] {http.py:129} INFO - Sending 'GET' to url:  https://random-data-api.com/api/v2/users/
[2022-10-17 10:38:30,378] {base.py:301} INFO - Success criteria met. Exiting.
[2022-10-17 10:38:30,489] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=is_api_available, execution_date=20220102T000000, start_date=20221017T103828, end_date=20221017T103830
[2022-10-17 10:38:30,623] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-17 10:38:30,778] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
