[2022-10-17 10:51:05,623] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.is_api_available manual__2022-10-17T10:51:03.915266+00:00 [queued]>
[2022-10-17 10:51:05,629] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.is_api_available manual__2022-10-17T10:51:03.915266+00:00 [queued]>
[2022-10-17 10:51:05,630] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:51:05,630] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-17 10:51:05,630] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:51:05,641] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-10-17 10:51:03.915266+00:00
[2022-10-17 10:51:05,646] {standard_task_runner.py:52} INFO - Started process 5054 to run task
[2022-10-17 10:51:05,650] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'is_api_available', 'manual__2022-10-17T10:51:03.915266+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpb_ptokqv', '--error-file', '/tmp/tmp0qr9i92s']
[2022-10-17 10:51:05,651] {standard_task_runner.py:80} INFO - Job 190: Subtask is_api_available
[2022-10-17 10:51:05,694] {task_command.py:369} INFO - Running <TaskInstance: my_first_dag.is_api_available manual__2022-10-17T10:51:03.915266+00:00 [running]> on host 48b5b9061ccc
[2022-10-17 10:51:05,768] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-10-17T10:51:03.915266+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-17T10:51:03.915266+00:00
[2022-10-17 10:51:05,770] {http.py:97} INFO - Poking: users/
[2022-10-17 10:51:05,782] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-10-17 10:51:05,786] {http.py:129} INFO - Sending 'GET' to url:  https://random-data-api.com/api/v2/users/
[2022-10-17 10:51:08,864] {base.py:301} INFO - Success criteria met. Exiting.
[2022-10-17 10:51:08,885] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=is_api_available, execution_date=20221017T105103, start_date=20221017T105105, end_date=20221017T105108
[2022-10-17 10:51:08,927] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-17 10:51:08,962] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
