[2022-10-17 10:29:42,049] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.is_api_available backfill__2022-09-10T00:00:00+00:00 [queued]>
[2022-10-17 10:29:42,055] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.is_api_available backfill__2022-09-10T00:00:00+00:00 [queued]>
[2022-10-17 10:29:42,055] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:29:42,055] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-10-17 10:29:42,055] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:29:42,065] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-09-10 00:00:00+00:00
[2022-10-17 10:29:42,070] {standard_task_runner.py:52} INFO - Started process 9567 to run task
[2022-10-17 10:29:42,072] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'is_api_available', 'backfill__2022-09-10T00:00:00+00:00', '--job-id', '89', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpio2ebef3', '--error-file', '/tmp/tmp6wlouict']
[2022-10-17 10:29:42,073] {standard_task_runner.py:80} INFO - Job 89: Subtask is_api_available
[2022-10-17 10:29:42,311] {task_command.py:369} INFO - Running <TaskInstance: my_first_dag.is_api_available backfill__2022-09-10T00:00:00+00:00 [running]> on host edecb506ad75
[2022-10-17 10:29:42,359] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-09-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=backfill__2022-09-10T00:00:00+00:00
[2022-10-17 10:29:42,360] {http.py:97} INFO - Poking: users/
[2022-10-17 10:29:42,367] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-10-17 10:29:42,368] {http.py:129} INFO - Sending 'GET' to url:  https://random-data-api.com/api/v2/users/
[2022-10-17 10:29:43,478] {base.py:301} INFO - Success criteria met. Exiting.
[2022-10-17 10:29:43,487] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=is_api_available, execution_date=20220910T000000, start_date=20221017T102942, end_date=20221017T102943
[2022-10-17 10:29:43,513] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-17 10:29:43,621] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
