[2022-10-17 10:38:27,860] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.is_api_available backfill__2022-01-13T00:00:00+00:00 [queued]>
[2022-10-17 10:38:27,960] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.is_api_available backfill__2022-01-13T00:00:00+00:00 [queued]>
[2022-10-17 10:38:27,963] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:38:27,964] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-17 10:38:27,964] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:38:28,310] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-01-13 00:00:00+00:00
[2022-10-17 10:38:28,394] {standard_task_runner.py:52} INFO - Started process 4313 to run task
[2022-10-17 10:38:28,441] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'is_api_available', 'backfill__2022-01-13T00:00:00+00:00', '--job-id', '129', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmplax3pgy9', '--error-file', '/tmp/tmp8ywtw3e9']
[2022-10-17 10:38:28,476] {standard_task_runner.py:80} INFO - Job 129: Subtask is_api_available
[2022-10-17 10:38:28,673] {task_command.py:369} INFO - Running <TaskInstance: my_first_dag.is_api_available backfill__2022-01-13T00:00:00+00:00 [running]> on host 48b5b9061ccc
[2022-10-17 10:38:28,890] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-01-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=backfill__2022-01-13T00:00:00+00:00
[2022-10-17 10:38:28,900] {http.py:97} INFO - Poking: users/
[2022-10-17 10:38:28,961] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-10-17 10:38:28,977] {http.py:129} INFO - Sending 'GET' to url:  https://random-data-api.com/api/v2/users/
[2022-10-17 10:38:30,102] {base.py:301} INFO - Success criteria met. Exiting.
[2022-10-17 10:38:30,178] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=is_api_available, execution_date=20220113T000000, start_date=20221017T103827, end_date=20221017T103830
[2022-10-17 10:38:30,290] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-17 10:38:30,640] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
