[2022-10-17 10:32:56,403] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.is_api_available manual__2022-10-17T10:32:54.309653+00:00 [queued]>
[2022-10-17 10:32:56,415] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.is_api_available manual__2022-10-17T10:32:54.309653+00:00 [queued]>
[2022-10-17 10:32:56,416] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:32:56,416] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-17 10:32:56,416] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:32:56,427] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-10-17 10:32:54.309653+00:00
[2022-10-17 10:32:56,433] {standard_task_runner.py:52} INFO - Started process 3957 to run task
[2022-10-17 10:32:56,437] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'is_api_available', 'manual__2022-10-17T10:32:54.309653+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp9y1spiwt', '--error-file', '/tmp/tmpiy_yrb29']
[2022-10-17 10:32:56,438] {standard_task_runner.py:80} INFO - Job 101: Subtask is_api_available
[2022-10-17 10:32:56,481] {task_command.py:369} INFO - Running <TaskInstance: my_first_dag.is_api_available manual__2022-10-17T10:32:54.309653+00:00 [running]> on host 48b5b9061ccc
[2022-10-17 10:32:56,530] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-10-17T10:32:54.309653+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-17T10:32:54.309653+00:00
[2022-10-17 10:32:56,531] {http.py:97} INFO - Poking: users/
[2022-10-17 10:32:56,537] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-10-17 10:32:56,539] {http.py:129} INFO - Sending 'GET' to url:  https://random-data-api.com/api/v2/users/
[2022-10-17 10:32:57,503] {base.py:301} INFO - Success criteria met. Exiting.
[2022-10-17 10:32:57,521] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=is_api_available, execution_date=20221017T103254, start_date=20221017T103256, end_date=20221017T103257
[2022-10-17 10:32:57,568] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-17 10:32:57,635] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
